### ISSUE TITLE
qBittorrent check version

### ISSUE THREAD

**Issue by COTMO** [Feramance/qBitrr#136]
qBittr: v4.9.19
qBittorrent: 5.0.1
Docker on Synology

Since the latest update v4.9.19. The docker starts up and just quits after the qBittorrent version check..
Probably caused because this change:
![image](https://github.com/user-attachments/assets/223f0489-d5ac-4745-835b-efd34ce68605)

**Comment by Feramance** [comment]
Yes, this is intentional for the time being as the API for qbittorrent v5 is not yet stable and has a number of issues so I had to limit the support for the time being, What I will do when I have the time is have a separate docker image for qbittorrent v5 which will have some issues and used at your own risk. For the time being I suggest sticking with qbittorrent v4

**Comment by Feramance** [comment]
Actually, just published an update now with a new config to allow qbittorrent v5. Take a look at the config example and search for `v5`

**Comment by COTMO** [comment]
Thanks for the quick response. Problem solved. The docker keeps running.
